### ISSUE TITLE
PymodeRun does not show errors during execution

### ISSUE THREAD

**Issue by ps-aux** [klen/python-mode#481]
When execution stops due to error it is not shown in run window which only shows standard output stream.

**Comment by JGideon** [comment]
Did this problem fix?

**Comment by klen** [comment]
Fixed, thank you for the feedback.

**Comment by yuhui-lin** [comment]
The error window shows only when the first time running python. After I modify the code, the error does not appear anymore (there is still an error).
I have to restart the vim and the error window shows up again.
Does anyone have the same problem???
